apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: rating-app
data:
  MONGO_URI: "mongodb://admin:password@mongo-0.mongodb-svc.rating-app.svc.cluster.local:27017/rating_app?directConnection=true&authSource=admin"
  PORT: "5000"
  FRONTEND_URL: "http://localhost:8080"

  # mongodb://admin:password@mongo-0.mongodb-svc.rating-app.svc.cluster.local:27017/rating_app?directConnection=true&authSource=admin
