apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
immutable: false # will not be update from commands
data:
  mongodb.conf: |
    storage:
      dbPath: /data/db
    replication:
      replSetName: "rs0"